### ISSUE TITLE
Missing or unsuitable terminal: alacritty

### ISSUE THREAD

**Issue by paulriddle** [hashbang/shell-server#122]
On [alacritty](https://github.com/alacritty/alacritty) upon connection to the server it says:
```
error connecting to /tmp//tmux-12601/default (No such file or directory)
open terminal failed: missing or unsuitable terminal: alacritty
```
Then it appears to be working ok, until you open a man page and it breaks visually. Everything works fine if I set `TERM=rxvt-unicode-256color`. I've encountered this error before, and I think it is fixed either by updating the complaining software or adding alacritty to the list of legit terminals. Something related to terminfo.

It's not clear what is even complaining about the terminal. tmux?

**Comment by dpflug** [comment]
Run `infocmp | ssh de1.hashbang.sh "tic -x -"` locally and it'll copy the needed terminfo entry to the server.

**Comment by paulriddle** [comment]
Copied. It seems to be connecting with `TERM=alacritty` just fine now.

**Comment by Karrq** [comment]
I'm having the same issue now...
