### ISSUE TITLE
Restore permission of HOME directory at startup.

### ISSUE THREAD

**Issue by qdtjvszxc** [hashbang/shell-server#127]
I made some mistake when trying to set permission of HOME directory:
```
qdtjvszxc@de1:~$ chmod -rwx ~
```
Now its permission becomes:
```
qdtjvszxc@de1:~$ ls -ld ~
d---r-xr-x 1 qdtjvszxc qdtjvszxc 426 Oct 29 03:59 ../qdtjvszxc
```
When I re-login into my account, it is still a problem:
```
Could not chdir to home directory /home/qdtjvszxc: Permission denied
fatal: could not create work tree dir '/home/qdtjvszxc/.dotfiles': Permission denied
CRITICAL: Failed to clone your dotfiles from
          https://github.com/hashbang/dotfiles
rm: cannot remove '/home/qdtjvszxc/.dotfiles': Permission denied
-bash: /home/qdtjvszxc/.bash_profile: Permission denied
qdtjvszxc@de1:/$ 
```
Please provide a way to restore its permission at startup.
Also an account removal procedure would be a easier way for it. [https://github.com/hashbang/hashbang.sh/issues/62](url)

**Comment by daurnimator** [comment]
You should be able to run commands with ssh yourself to fix it e.g. `ssh de1.hashbang.sh chmod +rwx .`

**Comment by qdtjvszxc** [comment]
It's my fault. Actually, `chmod +rwx .` doesn't help, but `chmod +rwx /home/qdtjvszxc` does. Sorry for that.
