### ISSUE TITLE
Couldn't send email to bender@shell.hashbang.sh

### ISSUE THREAD

**Issue by tetsuharu** [hashbang/shell-server#33]
Sending email from Mutt to my email address worked.
Replying to the email did not work.

![screen shot 2014-10-14 at 11 21 01 am](https://cloud.githubusercontent.com/assets/248656/4634464/8a00c1b8-53d0-11e4-8d57-4dca16e9a2c0.png)

**Comment by AlissaSquared** [comment]
Tested on my client. Works.
