### ISSUE TITLE
Account Creation Bad Request

### ISSUE THREAD

**Issue by arizen** [hashbang/shell-server#38]
As i was following the tutorial on the .sh file, it told me that it's going to create an account, but it returned a json file like that,

Creating your account...
{
 "message" : "Bad Request",
"status" : 400
}
Account created!

If i try to login with ssh, it's asking me for my password which is not provided to me :) I guess there is a problem with account creation.

**Comment by AlissaSquared** [comment]
Probably fixed as of recently (and I am quite confused on the 400 error and then "Account created," although I assume this is fixed as of my latest PR), and as user said, PEBKAC.
