### ISSUE TITLE
CI failing due to keyserver problems

### ISSUE THREAD

**Issue by Tunas1337** [hashbang/shell-server#82]
CI hangs on the step of adding administrator keys, does not output for 10 minutes and fails.
Example:
https://travis-ci.org/hashbang/shell-server/builds/445770246

**Comment by RyanSquared** [comment]
@lrvick a while ago, the topic was brought up about keeping users keys tracked in the repository. the above demonstrates it's becoming an issue. should we look into that again?

**Comment by RyanSquared** [comment]
this also causes issues with the deployed ansible-pull unit, so servers aren't automatically updated for at least days at a time.

**Comment by RyanSquared** [comment]
Closing (see https://github.com/hashbang/keyring - keys are now managed via repository).
