### ISSUE TITLE
Package request: tcsh

### ISSUE THREAD

**Issue by matthiaslandwehr** [hashbang/shell-server#87]
To make the list of login shells complete, I'd like to take tcsh installed & in /etc/shells.

**Comment by drGrove** [comment]
@matthiaslandwehr please make a pull request adding the package here: [ansible/tasks/packages/main.yml#L20](https://github.com/hashbang/shell-server/blob/master/ansible/tasks/packages/main.yml#L20)

**Comment by sjas** [comment]
sorry for the add-remove-add, i was still coming to terms how to use github :o)

**Comment by benharri** [comment]
tcsh seems to be installed currently
